import type { Metadata } from "next";
import { Geist, Geist_Mono, Big_Shoulders_Stencil_Display, Rationale } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/ui/nav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bigShoulderStencil = Big_Shoulders_Stencil_Display({
  variable: "--font-big-shoulder-stencil",
  subsets: ["latin"],
});

const rationale = Rationale({
  variable: "--rationale",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bigShoulderStencil.variable} ${rationale.variable} antialiased bg-black`}
      >
        <main>
          <Navbar/>
        </main>
        {children}
      </body>
    </html>
  );
}
